### ISSUE TITLE
Wrong reference in Exercise 13.6

### ISSUE THREAD

**Issue by jgaeb** [avehtari/ROS-Examples#102]
It appears that Exercise 13.6 on p. 238 has a mistake. It references the logistic model with an interaction between distance and arsenic, and the same model with the predictors centered (i.e., `fit_4` and `fit_5`) in Section 13.7. Those models don't actually seem to be introduced until Section 14.2.

**Comment by andrewgelman** [comment]
Oh, you're right!  That's kind of annoying.  I can't really move it to chapter 14 because that will screw up the numbering of the exercises, so I'll just keep it as exercise 13.6, and it will be referring forward to Section 14.2.
