### ISSUE TITLE
Slope values for example regression line 0.27 or 0.28

### ISSUE THREAD

**Issue by hachiko1024** [avehtari/ROS-Examples#105]
On pages 82-83 
The slope is on the one hand (labeled on graph) 0.27 and also 0.28 (In the table) - maybe confusion about rounding

**Comment by avehtari** [comment]
Not a rounding issue, but variability of the computation. Based on MAD_SD of 0.02 shown in p. 82, values of 0.26, 0.29, 0.30 are likely outputs when the computation is repeated. It would have been useful to include in the book explicit discussion of how small variation is natural. But as we didn't emphasise that the values can vary, I have changed the plot to show the same value as in p. 82.
