### ISSUE TITLE
Section 11.6 - text related to figure 11.16

### ISSUE THREAD

**Issue by leynu** [avehtari/ROS-Examples#118]
Hi,

Text on page 170 states: _"Even though R2 is much lower in Figure 11.16a, the model fits the data just as well as in
Figure 11.16b."_
However, if you look at figure 11.16a the R2 value is 30% and in figure 11.16b it is 10%. I assume the text should have been:
"Even though R2 is much lower in Figure **11.16b** the model fits the data just as well as in
Figure **11.16a**."

What do you think?
Kind regards,
Leyla

**Comment by avehtari** [comment]
Thanks for reporting this. I guess you are reading the paper copy. This has already been fixed for the forthcoming printings and the online version. This was missing from the errata, but I just added it there
