### ISSUE TITLE
Minor typo on p.159

### ISSUE THREAD

**Issue by rs4606** [avehtari/ROS-Examples#121]
On p. 159, right after the subsection heading "Forming a linear predictor from a multiple regression" in the sentence "Now extend the previous example so that the treatment indicator z is accompanied by k pre-treatment
predictors x_k, k = 1, . . . , K:" it should read "...is accompanied by K pre-treatment predictors x_k, k = 1, ..., K:" (i.e., there are K predictors).

**Comment by avehtari** [comment]
Thanks! Fixed
