### ISSUE TITLE
P. 436 and P. 439

### ISSUE THREAD

**Issue by rs4606** [avehtari/ROS-Examples#123]
Hi there,

1) I believe there is a typo on P. 436. In the first full paragraph, should y^{rep} instead be y^{adj}?

2) I believe there is a typo on P. 439. In the third paragraph (defining the monotonicity assumption), I believe the word "eligible" should be replaced by "ineligible", so the second sentence in that paragraph (describing what it means for there to be no defiers) would instead say "That is, there cannot be observations that would receive the treatment if they fall on the side of the cutoff that makes them ineligible but would not receive it otherwise."

Thanks,

Ravi

**Comment by andrewgelman** [comment]
Thanks!
