### ISSUE TITLE
P.194 - P.195 log-log model

### ISSUE THREAD

**Issue by ksnikiforov** [avehtari/ROS-Examples#124]
This paragraph suggests that the relationship between x and y is linear for log-log transformation, when in fact it is not.
<kbd>
<img width="500" alt="image" src="https://user-images.githubusercontent.com/50662246/216851549-c5ca451f-95b6-43c0-b9e5-3643933736cf.png">
</kbd>

I'm using this article as a reference \
[https://medium.com/@kyawsawhtoon/log-transformation-purpose-and-interpretation-9444b4b049c9](url)
<kbd>
<img width="500" alt="image" src="https://user-images.githubusercontent.com/50662246/216851950-54e6b0b8-a902-4804-9dbd-fbfccb70aafa.png">
</kbd>

So the correct statement should be that for a one percent change in $X$, $y$ changes by ${1.01}^{1.62}$\
The difference is small for small percent changes, but for large changes exponential formula gives vastly different results.

**Comment by andrewgelman** [comment]
The statement in the book is essentially correct.  When x is multiplied by 1.01, this corresponds to increasing log x by log(1.01) = 0.01, which corresponds to increasing log y by 0.0162, which corresponds to multiplying y by exp(0.0162) = 1.0162.  OK, actually 1.0163 but that's close enough.  I'll add "approximately" to clarify.
