### ISSUE TITLE
"Parameter of interest" (Sec 16.6, Pg 307)

### ISSUE THREAD

**Issue by jerome-white** [avehtari/ROS-Examples#125]
In section 16.6, subsection "Simulating a randomized experiment", page 307, the second paragraph states:

> ... we should focus on the standard error of the parameter of interest (in this case, 4.0)...

Where does that 4.0 come from? There is mention of a standard error of 4.3 in prior paragraphs (in the same section), but I can't find 4.0. A standard error of 4.0 does show up a paragraph later when the simulation is repeated. Is it referring to that?

This appears in both my Kindle (2020 Nov) and my paperback edition (ISBN 978-1-107-67651-0)

**Comment by andrewgelman** [comment]
Yes, it should say 4.3, thanks.
