### ISSUE TITLE
Cutpoint inclusivity (Sec 15.5)

### ISSUE THREAD

**Issue by jerome-white** [avehtari/ROS-Examples#126]
In the cutpoint equations presented in Section 15.5 (Eq. 15.7, 15.8, 15.9, and 15.10), the intervals for the discrete outcome variable seem exclusive. From Eq. 15.7 for example:

```
y_i = {
   1 if z_i < 0,
   2 if z_i \in (0, c_2),
   ...,
}
```

Should the intervals be left-inclusive? So `2 z_i \in [0, c_2)` instead?

This appears in both my Kindle (2020 Nov) and my paperback edition (ISBN 978-1-107-67651-0)

**Comment by andrewgelman** [comment]
Yes, you're literally correct but it doesn't matter because the distribution is continuous so there's probability zero of being right on any boundary.
