### ISSUE TITLE
Bayesian inference (p. 15) and Exercise 9.6

### ISSUE THREAD

**Issue by wviechtb** [avehtari/ROS-Examples#128]
The Bayesian inference results given for the 'Jamaica childhood intervention' study are slightly off. The estimate is given as 1.42 with a 95% CI of [1.02, 1.98]. We log transform the estimate and can then recalculate its SE with:

```r
estimate <- log(1.42)
stderr <- (log(1.98) - log(1.02)) / (2*1.96)
```

We can double-check that this is correct by calculating again the CI under classical inference with `round(exp(estimate + c(-1,1) * 1.96 * stderr), digits=2)`.

The posterior estimate and its standard error are calculated with:

```r
estimate.post <- weighted.mean(c(0,estimate), 1/c(.10,stderr)^2)
stderr.post <- 1/sqrt(sum(1/c(.10,stderr)^2))
```

based on which we can compute the estimate on the multiplicative scale and the 95% posterior interval with:

```r
round(exp(estimate.post), digits=2)
round(exp(estimate.post + c(-1,1) * 1.96 * stderr.post), digits=2)
```

which yields an estimate of 1.10 with 95% PI [0.92, 1.30] (and not 1.09 with PI [0.92, 1.28]).

**Comment by andrewgelman** [comment]
Thanks!
