### ISSUE TITLE
[Optional Suggestion] Show df head for NES Predictions

### ISSUE THREAD

**Issue by canyon289** [avehtari/ROS-Examples#15]
It would be nice for readers if in the code `linpred`, `epred` and `postpred` showed their first 5 rows and perhaps `str(df)` as well for shape.

That way its very obvious what different is in each one of these methods at a glance and the reader doesn't need to run the code locally. The explanation on page 239 makes some sense as to what is happening, but the docs are a bit hard to decipher.

https://avehtari.github.io/ROS-Examples/NES/nes_logistic.html
![image](https://user-images.githubusercontent.com/7213793/88488248-cc42ae00-cf40-11ea-8d9e-ef32e8d937b3.png)
https://www.rdocumentation.org/packages/rstanarm/versions/2.19.3/topics/posterior_predict.stanreg
https://www.rdocumentation.org/packages/rstantools/versions/2.1.1/topics/posterior_epred

PS 
I will label issues that are "personal preference" as optional suggestion. Feel free to close without resolution if you disagree I wont be offended

**Comment by avehtari** [comment]
Thanks for the suggestion, I added this.
