### ISSUE TITLE
Cannot find some code in Chapter 13

### ISSUE THREAD

**Issue by canyon289** [avehtari/ROS-Examples#16]
There is some code block that is in Chapter 13 that I cannot seem to find in the associated code files. Any help would be great, hopefully I am not just blind

![image](https://user-images.githubusercontent.com/7213793/88488656-8b986400-cf43-11ea-8864-4f2e10991598.png)

`This the notebooks I'm looking in`
![image](https://user-images.githubusercontent.com/7213793/88488660-95ba6280-cf43-11ea-9031-0cc64c6b89cc.png)

**Comment by avehtari** [comment]
There are some small amount of code in the book that doesn't have R file in repo. This is one of those cases.
