### ISSUE TITLE
Missing "healthdata.txt" file

### ISSUE THREAD

**Issue by jbandlow** [avehtari/ROS-Examples#17]
On page 26 (Section 2.3) of the printed book, an example begins with
```
health <- read.table("healthdata.txt", header=TRUE)
```
The file `healthdata.txt` is not present in the repo, although more complex code for reproducing the graph in Figure 2.4 is present in `HealthExpenditure/healthexpenditure.R`.

**Comment by avehtari** [comment]
Thanks for reporting. Andrew had changed this in the last moment before sending the manuscript to the print and forgot to send the updated code to me. The code has been now updated and the data file is now in the repo.
