### ISSUE TITLE
two minor typos

### ISSUE THREAD

**Issue by rs4606** [avehtari/ROS-Examples#20]
-p.39, in the second sentence of the first full paragraph, "Figure 3.4 displays data on log metabolic rate vs. body mass indicating..." should perhaps be "log metabolic rate vs. log body mass" since both variables are on the log scale.
-p.54, in "Comparisons, visual and numerical" subsection, "Figure 4.2" in the first sentence should be "Figure 4.3."

**Comment by avehtari** [comment]
Thanks! There is now errata in the web page including these (and I fixed these in the book)
