### ISSUE TITLE
page 11. difference between treatments and controls

### ISSUE THREAD

**Issue by dipetkov** [avehtari/ROS-Examples#21]
On page 11 [Kindle version], the summary of the treatment-control comparison says "the treated units were 4.8 points higher than the controls, \bar{y} = 31.7 under the treatment and  \bar{y} = 25.5 for the controls." Isn't the difference in means 6.2?

I also looked at the code in SimpleCausal/causal.R. It seems that the random seed was not fixed and so the simulations and the analyses might not be fully reproducible.

**Comment by avehtari** [comment]
Thanks for the report. 
The difference 4.8 is a mistake after Andrew had made changes to other values. I added this to the errata.

Setting random seed makes R base random functions reproducible and we have set the seed in some cases. When running Stan, setting the seed doesn't guarantee reproducability as different operating systems and compilers don't guarantee that floating point operations are made in the same order which can lead to small differences which can lead to big differences in MCMC realizations even if the long run behavior is valid. See more in Stan manual. I'll add a comment to the causal.R
