### ISSUE TITLE
Ch. 17, p. 316, poststratification data mismatch

### ISSUE THREAD

**Issue by noahaskell** [avehtari/ROS-Examples#24]
On p. 316, the data given in the code for `poststrat_data_2` does not match the data shown in the table that it is meant to correspond to (Figure 17.2).

More specifically, the values for `N` in `poststrat_data_2` are 0.16, 0.17, 0.19, 0.17, 0.16, 0.15, but in the table in Figure 17.2 the values are 0.16, 0.17, 0.22, 0.14, 0.14, 0.17.

**Comment by avehtari** [comment]
Thanks! Added to the errata and fixed for the future printings.
