### ISSUE TITLE
Poststratification using a weighted average, Chapter 17, page 314

### ISSUE THREAD

**Issue by misterblister** [avehtari/ROS-Examples#26]
Following Equation (17.1) the text says (in part)

"... which was too low because the sample did not include enough Republicans."

But as I read it, the sample had just the right fraction of Republicans, namely 33%. Instead it had too many Democrats and not enough Independents.

**Comment by avehtari** [comment]
Thanks! Fixed to have "... which was too low because the sample included too many Democrats." and added to errata.

**Comment by avehtari** [comment]
@misterblister, in the next printing of the book, we are thanking all who sent us corrections. As Mister-Blister is name of a company, we are hesitating to list "misterblister". Would you like to tell your real name or stay anonymous?

**Comment by misterblister** [comment]
Thanks. Use my real name. —Mark

Mark Fisher
mark@markfisher.net
770-710-7746

**Comment by avehtari** [comment]
Thanks!
