### ISSUE TITLE
[optional]: soft coding text in figure 7.4 code

### ISSUE THREAD

**Issue by Rmadillo** [avehtari/ROS-Examples#29]
The means are currently hardcoded in the code for figure 7.4. Using `bquote` instead of `expression` could allow for whatever the simulation's means were in the plot in `simplest.R` lines 122 and 123:

`text(.05, -1 + mean(y[x==0]), bquote(paste(bar(y)[0], " = ", .(round(mean(y[x==0]), 2)))), col="gray30", cex=.9, adj=0)`

`text(.95, 1 + mean(y[x==1]), bquote(paste(bar(y)[1], " = ", .(round(mean(y[x==1]), 2)))), col="gray30", cex=.9, adj=1)`

LOVE the book!

**Comment by avehtari** [comment]
Thanks for the suggestion! I changed the code.
