### ISSUE TITLE
Typo on page 143 'Predictive simulation for a nonlinear function of new data'

### ISSUE THREAD

**Issue by eamonn2014** [avehtari/ROS-Examples#30]
On page 143 3rd line from bottom '...Figure 10.7 give a predictive mean of 260.1...'. I think this should be 262.1. Thanks for the great book. Eamonn.

**Comment by avehtari** [comment]
Thanks! Fixed. The code in congress.R gives mean 260.0 or 260.1 and sd 2.4 or 2.5
depending on the random seed. The book has now values 260.1 and 2.5. Added to the errata.
