### ISSUE TITLE
Minor typo in the description of the parameters of the rss function (Chapter 8, p. 105)

### ISSUE THREAD

**Issue by RaulPL** [avehtari/ROS-Examples#32]
I have the eBook version of the book. In the second paragraph of page 105 I think there is an error. It says:

We can try it out: ```rss(hibbs$growth, hibbs$vote, 46.3, 3.0)``` evaluates the residual sum of squares at the least squares estimate, ```(a,b) = (46.2, 3.1)``` ...

I think the last part should be ```(a,b) = (46.3, 3.0)```, or the other way around since the values (46.2, 3.1) are used in the following sections of the chapter.

**Comment by avehtari** [comment]
Thanks! Since the computation is stochastic, different runs can produce slightly different values. Of course it would be good to be consistent in the book. I'll change these.
