### ISSUE TITLE
I think I noticed an errata on the book: page 217. 

### ISSUE THREAD

**Issue by VicentModesto** [avehtari/ROS-Examples#33]
I think I noticed an errata on the book. In page 217, it can be read: "The logistic function, logit(x) = log(x/1-x), maps the range (0,1) to (-inf to +inf)...". I think this is a mistake. It should be: "The logit function, logit(x) = log(x/1-x), maps the range (0,1) to (-inf to +inf)...". 
I think the logistic function is the INVERSE of this logit function.

I think also that in page 219, it can be read: "The inverse logistic function is curved, and so the expected difference..." I don't know waht shape has the inverse logistic function. But I think that the text is more understandable, for the standard classical statistics readers like me, if you write "The inverse logit function (the logistic function) is curved, and so the expected difference...". This is my opinion.

Thanks

**Comment by avehtari** [comment]
Thanks! Added to the errata and fixed for the future printings.

**Comment by VicentModesto** [comment]
Thank you very much to you. It's a splendid book!! I'm looking forward the
second part, about hierarchical models.

Vicent Modesto

El dc., 9 de set. 2020, 21:17, Aki Vehtari <notifications@github.com> va
escriure:
