### ISSUE TITLE
Figures are not labeled with (a), (b) and so on throughout the book plus a question

### ISSUE THREAD

**Issue by zhengchencai** [avehtari/ROS-Examples#34]
Hi there,

I was on page 208. In the middle of the page. One paragraph says "Figure12.11a shows that with the default prior on regression coefficients and sigma, the implied prior distribution of R^2 is strongly favouring larger values and thus is favouring overfitted models". However, the prior distribution looks like an exp distribution, why do you think it is strongly favouring larger values? Is this inference coming from the posterior? it makes sense to state this looking at the posterior not prior.  Besides, I barely see the differences between the three prior distributions visually. The very right one should be a horseshow prior but sill looks like an exp. I might be wrong since I did not understand very well this section 12.7. 

In general, there are no labels for (a), (b), (c) and so on in the figures of the book, it is not at all a problem because I could understand well with the nice captions, but not sure if this is good for formal textbook.

Thanks,
Zhengchen

**Comment by avehtari** [comment]
Thanks for reporting this @zhengchencai! This is very embarrassing as the top row has the same plot repeated three times! All the prior plots are showing the regularized horseshoe prior! The notebook has correct figures https://avehtari.github.io/ROS-Examples/Student/student.html, and I can't understand how it is possible that at some point the last plot was saved to all three figure files for the book. I clearly remember that it was ok at some point. Re-running the figure generation produces the correct plots. The future printings will have this fixed and the correct figure 12.11 is shown in [the errata](https://avehtari.github.io/ROS-Examples/errata.html)
