### ISSUE TITLE
Potential issue with "fishing" formula on p61

### ISSUE THREAD

**Issue by kjytay** [avehtari/ROS-Examples#38]
Hi, thanks very much for the book! I enjoyed reading through it. :)

This is the first of a number of typos/issues I spotted while going through the book. I've put one typo/issue in each issue for easier reference.

p61 near the bottom of the page: It says computing T(y;\phi(y) for j = 1, \dots, J, but j doesn't appear in the formula.

Also, I found the notation a little confusing. It appears that T represents the test statistic while \phi represents the choices in the analysis. So, when choosing the best result given the data, shouldn't it be T^{best} instead of \phi^{best}, since we are performing J tests (presumably on different statistics)?

**Comment by andrewgelman** [comment]
Yes, in item 4 on that list on page 61, phi(y) should be phi_j(y).

**Comment by avehtari** [comment]
Thanks @kjytay! Fixed and added to the errata.
