### ISSUE TITLE
Broken link!

### ISSUE THREAD

**Issue by dante042** [avehtari/ROS-Examples#4]
Hello!

I think that there is a broken link here!

 https://avehtari.github.io/ROS-Examples/PoissonExample/PoissonExample.html

**Comment by jgabry** [comment]
Thanks for reporting. This will be fixed by #5 but I think @avehtari is on vacation at the moment. Until then you can use this link for the Poisson example, which should work: 

https://avehtari.github.io/ROS-Examples/PoissonExample/poisson_regression.html
