### ISSUE TITLE
Typo on P43: standard deviation subscripts change between 1st and 2nd paragraphs

### ISSUE THREAD

**Issue by braden-scherting** [avehtari/ROS-Examples#48]
In the print version of the book, section "Mean and standard deviation of the sum of correlated variables" (p43) displays standard deviations as \sigma_{a} and \sigma_{b} in paragraph 1. In paragraph 2, when discussing linear combinations, this changes to \sigma_{u} and \sigma_{v}. Mean subscripts remain unchanged throughout.

**Comment by andrewgelman** [comment]
Yes, they should be sigma_u, sigma_v in both places.  Good catch!

**Comment by avehtari** [comment]
Thanks! Fixed and added to the errata.
