### ISSUE TITLE
Typo in p-value calculation in R on p. 57

### ISSUE THREAD

**Issue by reppertj** [avehtari/ROS-Examples#51]
I'm new to R, so there may be a misunderstanding on my part, but I believe there is a typo in the p-value calculation on page 57:

```R
2*(1 - pt(abs(theta_hat)/se_theta, n_c+n_t, 2))
```

should be
```R
2*(1 - pt(abs(theta_hat)/se_theta, n_c+n_t-2))
```

By the way, the book has been excellent so far!

**Comment by avehtari** [comment]
Thanks! You are correct, I fixed this and added to the errata.
