### ISSUE TITLE
Exercise 3.8 seems to be missing

### ISSUE THREAD

**Issue by omrihar** [avehtari/ROS-Examples#52]
Both exercise 9.6 (page 128) and the description of the jamaican study refer to Exercise 3.8, which is supposed to calculate the multiplicative factor distribution. However, exercise 3.8 deals with the mean and standard deviation of correlated heights, rather than with the jamaican study.

**Comment by ettieunwin** [comment]
I was wondering if it was supposed to be example 4.8 instead which talks about the Jamaican study

**Comment by omrihar** [comment]
I think you may be right and it is exercise 4.8. I skipped it when reading this chapter, and couldn't find it when looking back from exercise 9.6. So, it's a typo on page 128 *and* 15.

**Comment by avehtari** [comment]
Thanks for both! I fixed this and added to the errata.
