### ISSUE TITLE
Figure 7.2(b) y-intercept

### ISSUE THREAD

**Issue by profjhg** [avehtari/ROS-Examples#53]
The fit linear model has an intercept of 46.3 but the graph shows the line intersecting the vertical axis at around 44, clearly below 45. either the line is not from this model or the axis is incorrectly labeled.

**Comment by mgrabovsky** [comment]
I think you're reading the graph incorrectly. The y-axis intercept is actually at the 0% growth point on (as denoted on the x-axis).

In the following picture, I've coloured the (virtual) y-axis red. The green horizontal segments mark the points 45%, 46%, …, 50% on the y-axis. The regression line clearly intercepts slightly above 46%.
![bitmap](https://user-images.githubusercontent.com/134321/95123125-c5f75c00-0751-11eb-9b67-5ea75ecaf392.png)

**Comment by avehtari** [comment]
Thanks @mgrabovsky, you are right. It might help to add an vertical line at 0%
