### ISSUE TITLE
Mistakenly labelled equation on page 385

### ISSUE THREAD

**Issue by mgrabovsky** [avehtari/ROS-Examples#54]
In the paragraph following equation 20.2 on p. 385, we can read

> Equating the coefficients of _z_ in (20.1) and (20.2) yields β₂* = β₁ + β₂γ₁.

However, there's no β₂* in equation 20.1. I believe the second equation in the subsection (the one with starred β's) should be marked as (20.1).

**Comment by avehtari** [comment]
Thanks! Fixed for the future printings and added to the errata.
