### ISSUE TITLE
r quantile syntax in 5.3, page 73

### ISSUE THREAD

**Issue by reppertj** [avehtari/ROS-Examples#56]
The uncertainty intervals should be (something like)

```R
quantile(z, c(0.25, 0.755))
quantile(z, c(0.025, 0.975))
```

instead of

```R
quantile(z, 0.25, 0.75)
quantile(z, 0.025, 0.975)
```

Again, really enjoying the book!

**Comment by avehtari** [comment]
Thanks! Fixed for the future printings and added to the errata.
