### ISSUE TITLE
Cannot load RDA file in R

### ISSUE THREAD

**Issue by canyon289** [avehtari/ROS-Examples#6]
Hi Aki,
I am unable to load this RDA file in R and am unsure what this error message means. If possible it would be helpful if the sexdata datafile was in a language agnostic format like csv, or txt or such so it can be loaded directly using Python
https://github.com/avehtari/ROS-Examples/tree/master/SexRatio/data

![image](https://user-images.githubusercontent.com/7213793/87260149-f7b79a00-c464-11ea-8da2-2f2ee580d6ca.png)

**Comment by briatte** [comment]
Update to R 4.0.0, perhaps?

```
R version 4.0.0 (2020-04-24) -- "Arbor Day"
Platform: x86_64-apple-darwin17.0 (64-bit)

r$> load("~/Downloads/sexratio.rda")

r$> ls()
[1] "sexratio"

r$> sexratio
   x  y
1 -2 50
2 -1 44
3  0 50
4  1 47
5  2 56

r$>
```

**Comment by canyon289** [comment]
Sounds so obvious when you say it :). I didnt know rda was version dependent, now I do. Thanks. Will close when I figure it out

**Comment by briatte** [comment]
The documentation for `load` and `save` is not that clear, but the page for `readRDS` has some (too few) details.

**Comment by canyon289** [comment]
@briatte, Thanks for the help here. Updated to R version 4 and converted things to csv. As a suggestion it would be more convenient if a csv was also provided in a github, but more than anything appreciate you helping me get unstuck
