### ISSUE TITLE
Minor typo

### ISSUE THREAD

**Issue by rs4606** [avehtari/ROS-Examples#61]
Hi,

On p.183 (first page of chapter 12), in the 4th line from the bottom of the page, it reads
"...difference in height is $1600*3.8 = $63*97 = $101 000 000*0.000 060 = $610, which is reasonably..."
but the rightmost quantity should be (approximately) $6100, not $610.

Thanks,

Ravi

**Comment by avehtari** [comment]
Thanks! Fixed for the future printings and will appear in errata.
