### ISSUE TITLE
Numerical typo on p. 46

### ISSUE THREAD

**Issue by mikemc** [avehtari/ROS-Examples#65]
In the section "Using an reasonable-seeming but inappropriate probability model", 2nd paragraph, first sentence:

> ...that is, exactly 10 000 votes for each candidate...

should be 100,000 votes rather than 10,000 votes.

Minor: "an reasonable" in the section title should be "a reasonable"

**Comment by mikemc** [comment]
Oh sorry, I see this comment is the same as #63

**Comment by avehtari** [comment]
Thanks! Fixed based on #63
