### ISSUE TITLE
Sign errors and misreferenced figures on p. 344, 345, and 349

### ISSUE THREAD

**Issue by mikemc** [avehtari/ROS-Examples#66]
I haven't quite figured out what is the problem here but it seems that the sign of the estimated treatment effects is not being consistently stated. Just above the middle of p 344 says "...seen from Figure 18.2 that the true sample average treatment effect is -7.5", but the caption in Figure 18.2 has a calculation of 157.5-145 = 12.5, so perhaps what is meant is Figure 18.3 which has a calculation of 155-147.5, which should be +7.5, but is there stated to be -7.5. Then, just below the middle of p. 344 reads " ...Figure 18.1 yields a naive estimated treatment effect of -12.5." But Figure 18.1 shows a calculation of 157.5-145 = +12.5.

In p 349 section "Matched pairs experiments", "Figure 18.4" should instead be "Figure 18.3" (the balanced design)

**Comment by andrewgelman** [comment]
In this case the true avg effect is 7.5 in all cases.  But we did have some typos; thanks.

**Comment by avehtari** [comment]
Thanks! Fixed for future printing and relevant parts added to errata.
