### ISSUE TITLE
Minor typos and grammar mistakes on pages 53, 55, 178, 257, and 269

### ISSUE THREAD

**Issue by mikemc** [avehtari/ROS-Examples#67]
p. 53: "...unless we adjust for the parameters **estimated involved** in the fitting" - one word should be cut

p. 53: "...because ~~of~~ the mean is being estimated from..."

p. 55 First sentence of 4.3: "The inferences discussed above are all **consistent** on the model being true..." I think "contingent" was meant instead of "consistent"

p. 178: "For example, we can compute ~~and compute~~ LOO R^2..."

p. 257 "...using **a Bayesian prior information** to..." seems like the bolded phrase should be either  "a Bayesian prior" or "prior information"

p. 269: The sentence starting "The model predictions overall much closer than with Poisson model..." should be "the Poisson model" but more seriously I found "and especially the model is predicting much larger counts" confusing and think it could be cleared up with better grammar

**Comment by avehtari** [comment]
Thanks! Fixed for the future printings.
