### ISSUE TITLE
p. 397: Wrong numbers in standard error calculation

### ISSUE THREAD

**Issue by mgrabovsky** [avehtari/ROS-Examples#71]
On the last line on page 397 in the calculation of the standard error of the estimate, there are wrong numbers for the middle two groups in the numerator:
> 1.5² * 1358² + 1.9² * 1738² + 2.4² * 789² + 2.3² * 366²

should be

> 1.5² * 1358² + 1.9² * 1820² + 2.4² * 837² + 2.3² * 366²

The result is also incorrect, it should be 1.04.

**Comment by avehtari** [comment]
Thanks! Fixed and will be mentioned in the errata.
