### ISSUE TITLE
p.345 control/treatment group are switched

### ISSUE THREAD

**Issue by rs4606** [avehtari/ROS-Examples#73]
Hi there,

At the very bottom of p.345, it says "More to the point, the y_i^{0}'s are 140, 140, 150, and 170 in the control group and 150, 160, 160, and 170 in the treatment group."

However, looking at Figure 18.4, it appears as though the words "control" and "treatment" should be switched in the previous sentence. That is, the y_i^{0}'s for those with z_i = 0 (control group) are 150, 160, 160, 170, and the y_i^{0}'s for those with z_i = 1 (treatment group) are 140, 140, 150, and 170.

Thanks,

Ravi

**Comment by avehtari** [comment]
Thanks! Fixed for future printings and will appear in errata.
