### ISSUE TITLE
typo: `offset=log(exposure)`

### ISSUE THREAD

**Issue by ASKurz** [avehtari/ROS-Examples#76]
On page 268, the code for the first roaches model is: 

```{r}
fit_1 <- stan_glm(y ~ roach100 + treatment + senior, family=neg_binomial_2,
                  offset=log(exposure), data=roaches)
```

However, the *exposure* variable in the `roaches.csv` file is called `exposure2`.

**Comment by avehtari** [comment]
Thanks! Fixed and added to the errata.
