### ISSUE TITLE
Typo on page 231.

### ISSUE THREAD

**Issue by danieltimar** [avehtari/ROS-Examples#77]
Bottom of the page 231:

> Just using the fact that 59.5% of survey respondents supported Clinton and 40.5% supported Bush, we can assign 40.5% to Pr(yi = 1) for each respondent, which improves the log score to 477 log(0.405) + 702 log(**−.595**) = −796.

I presume it's log(0.595).

**Comment by avehtari** [comment]
Thanks! Fixed and added to the errata.
