### ISSUE TITLE
typo on page 299

### ISSUE THREAD

**Issue by ASKurz** [avehtari/ROS-Examples#82]
In the first paragraph on p. 299, we read:

> When compared to the average observed rate in the control group, the estimated treatment effect from this study is about half that of the Rosado et al. (1997) experiment: 1.8/8.1 = 0.22, compared to 0.5/1.15 = 0.43, which suggests a higher sample size might be required.

This is a little tricky to walk out because we're comparing Δ / 𝜇control in two studies, each of which was initially summarized with different mixtures of sample statistics. Even so, I believe the correction should read:

> ... 1.8/8.1 = 0.22, compared to 0.5/1.25 = 0.4 ...

This is because the "average observed rate in the control group" for the second study in the comparison (Rosado et al, 1997) is 1.25. We can compute this from the weighted mean taken from sample statistics in the first two rows of the top table in Figure 16.4:

```{r}
# sample sizes
n1 <- 56
n2 <- 54

# means
m1 <- 1.1
m2 <- 1.4

# weighted mean (i.e., the average observed rate of the composite control group of placebo and iron)
(m1 * n1 + m2 * n2) / (n1 + n2)
```

```
[1] 1.247273
```

Based on the rounding conventions y'all use in the text, this would have been simplified to 1.25.

**Comment by andrewgelman** [comment]
Sure, I guess that makes sense!

**Comment by avehtari** [comment]
Thanks! I added this also to errata.
