### ISSUE TITLE
misleading paragraph (p. 300)

### ISSUE THREAD

**Issue by ASKurz** [avehtari/ROS-Examples#83]
About 1/3 of the way down on page 300, we read:

> We illustrate with the example of the survey earnings and height discussed in Chapter 4. The coefficient for the sex-earnings interaction in model (12.2) is plausible (a positive interaction, implying that an extra inch of height is worth 0.7% more for men than for women), but it is not statistically significant—the standard error is 1.9%, yielding a 95% interval of [−3.1, 4.5], which contains zero.

This example seems misleading. I believe the `earnings.csv` data were first introduced in Chapter 5 (p. 74).The interaction model, `log(earn) ~ height + male + height:male`, was introduced in Section 12.4.3.4 (p. 193). However, the summary from that model was:

```
logmodel_3 <- stan_glm(log(earn) ~ height + male + height:male,
                       data=earnings, subset=earn>0)

print(logmodel_3, digits = 3)
```

```
stan_glm
 family:       gaussian [identity]
 formula:      log(earn) ~ height + male + height:male
 observations: 1629
 predictors:   4
------
            Median MAD_SD
(Intercept)  8.517  0.685
height       0.016  0.011
male        -0.873  1.062
height:male  0.018  0.016

Auxiliary parameter(s):
      Median MAD_SD
sigma 0.868  0.015 
```

I can see where one might interpret the standard error as 1.9% by multiplying 0.016 by 100 and accounting for simulation variation. Even still, my values for the 95% intervals of the interaction are very different from those reported in the paragraph:

```{r}
quantile(as.matrix(logmodel_3)[, "height:male"], probs = c(0.025, 0.975))
```

```
       2.5%       97.5% 
-0.01038078  0.04788369 
```

Am I missing something?

**Comment by avehtari** [comment]
Thanks! I added this also to the errata.
