### ISSUE TITLE
typo on p. 304

### ISSUE THREAD

**Issue by ASKurz** [avehtari/ROS-Examples#85]
Toward the bottom of the page, we read:

> For our discussion here we shall work with the simple analysis from Section 9.4, comparing the “very attractive” parents in the survey (56% of their children were girls) to the other parents (only 44% of their children were girls). The difference was 8% with a standard error of 3%.  (p. 304).

I believe the second percentage should be 48%, not 44%. To work it through, we first load the `sexratio.rda` data.

```
load("ROS-Examples-master/SexRatio/data/sexratio.rda")
```

Now we compute the average percentage among the rows for which `x < 2` (i.e., the first four rows).

```{r}
mean(sexratio$y[1:4])
```
```
[1] 47.75
```

This would have been rounded to 48. Also, when you incorporate the information from the last sentence in the block quote, 56 - 8 = 48.

**Comment by avehtari** [comment]
Thanks! fixed and added to the errata
