### ISSUE TITLE
Range of possible fits for election economy seemingly missing in html

### ISSUE THREAD

**Issue by canyon289** [avehtari/ROS-Examples#9]
In the HTML for hibbs.html the range of possible fits "seems to be missing" but I can see in the code its just commented out. Was a little disorienting as I read book because in Figure 8.2 the Median fit, and the range of fits are side by side, but it took a bit of searching to find the code and figure lower down in the .rmd file

https://github.com/avehtari/ROS-Examples/blob/master/ElectionsEconomy/hibbs.R#L161
https://avehtari.github.io/ROS-Examples/ElectionsEconomy/hibbs.html
![image](https://user-images.githubusercontent.com/7213793/87260881-e1134200-c468-11ea-8ccd-96f696244720.png)

**Comment by avehtari** [comment]
Fixed. Thanks for pointing out this!
