### ISSUE TITLE
typo in book and on Examples web page

### ISSUE THREAD

**Issue by brian-bucher** [avehtari/ROS-Examples#90]
Book page 267 and web page https://avehtari.github.io/ROS-Examples/PoissonExample/poisson_regression.html in the negative binomial model for overdispersion section:

```
for (k in 1:K){
  y_nb[[k]] <- rnegbin(n, exp(linpred), phi_grid[k])
  fake_nb[[k]] <- data.frame(x=x, y=y_nb[[k]])
  fit_nb[[k]] <- stan_glm(y ~ x, family=neg_binomial_2(link="log"), data=fake, refresh=0)
}
```

I believe the
```data=fake```
should be
```data=fake_nb[[k]]```

**Comment by avehtari** [comment]
Great catch! Fixed now in the book and the examples web page, and added to the errata.
