### ISSUE TITLE
Winner's curse example

### ISSUE THREAD

**Issue by jjw3952** [avehtari/ROS-Examples#92]
On pg 292 in the winner's curse example it states that given the situation described there is a 24% probability of the estimate being in the wrong direction. I cannot figure out how that 24% was arrived at so I think that's an error. There's about a 40% probability it's negative and about a 1.2% chance it's negative and two standard deviations below the true effect value.

**Comment by andrewgelman** [comment]
The book is correct.  0.24 = left shaded area / (left shaded area + right shaded area) = Pr(estimate is negative | estimate is statistically significantly different from zero).

**Comment by jjw3952** [comment]
Ahh, yes that makes sense. Sorry for the false alarm!
