### ISSUE TITLE
Typo in Exercise 10.2?

### ISSUE THREAD

**Issue by JakobStaudt** [avehtari/ROS-Examples#94]
In Exercise 10.2, part (a) reads:

Write the equation of the estimated regression line of y on x for the treatment group and the
control group, and the equation of the estimated regression line of y on x for the control
group.

Isn't the second part a duplicate of the first part? Are we supposed to do the control group twice?
I looked on https://avehtari.github.io/ROS-Examples/errata.html and didnt find this as an error.

**Comment by andrewgelman** [comment]
Yes, we'll fix this.

**Comment by avehtari** [comment]
Thanks! Fixed and added to the errata
