### ISSUE TITLE
Correction on p.187

### ISSUE THREAD

**Issue by rs4606** [avehtari/ROS-Examples#98]
Hi there,

I think the first sentence of the 'Multiplying each regression coefficient by 2 standard deviations of its predictor' subsection of Ch. 12 on p. 187 is incorrect, or perhaps unclear enough that it should be modified. 

The sentence reads "For models with no interactions, a procedure that is equivalent to centering and rescaling is to leave the regression predictors as is, and then create rescaled regression coefficients by multiplying each \beta by two times the standard deviation of its corresponding x." However, if the predictors don't each have mean 0, the intercept will change if one centers the predictors. 

Thanks,

Ravi

**Comment by andrewgelman** [comment]
Good point; we will fix.

**Comment by avehtari** [comment]
Thanks! Fixed and added to the errata
