### ISSUE TITLE
Clarification on p.183

### ISSUE THREAD

**Issue by rs4606** [avehtari/ROS-Examples#99]
Hi there,

I believe the last sentence on p.183 is not correct as written. The sentence says "Linear transformations of the predictors X or the outcome y do not affect the fit of a classical regression model, and they do not affect predictions; [...]"

However, linear transformations of the outcome do affect predictions (invertible linear transformations of the predictors do not). For example, if one multiplies the outcome by a constant (other than 1), then fits a linear regression, the fitted values will also change.

Thanks,

Ravi

**Comment by andrewgelman** [comment]
Sure, but they don't change the meaning of the predictions!  For example if you convert the outcome from Fahrenheit to Celsius, the numbers change but the actual predictions are the same.

**Comment by rs4606** [comment]
That's true; I think I was being pedantic!
